[project]
channels = ["conda-forge"]
description = "Add a short description here"
name = "ost"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
gxx = ">=14.1.0,<15"
cmake = ">=3.30.3,<4"
ninja = ">=1.12.1,<2"
abseil-cpp = ">=20220623.0,<20220624"
python = ">=3.12.5,<4"
